name: your-app-name
region: your-region
services:
  - http:
      path: /
      target: django
      static:
        path: /media
        dir: /app/media
      envs:
        DJANGO_SETTINGS_MODULE: Tulip.settings
