# Generated by Django 4.1.5 on 2023-10-04 15:16

import ckeditor.fields
from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("True", "Active"), ("False", "Not active")],
                        default="True",
                        max_length=50,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=200,
                        unique=True,
                        verbose_name="link",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("short_description", models.TextField(default="")),
                ("description", ckeditor.fields.RichTextField()),
                ("img",
                 models.ImageField(upload_to=blog.models.upload_image_path)),
                (
                    "create_at",
                    models.DateTimeField(auto_now=True,
                                         verbose_name="Created at"),
                ),
                (
                    "view_count",
                    models.BigIntegerField(default=0,
                                           verbose_name="View Count"),
                ),
            ],
        ),
    ]
