# Generated by Django 4.1.5 on 2023-02-23 11:38

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='bottom_video_url',
            field=models.URLField(blank=True, verbose_name='Bottom Video URL'),
        ),
        migrations.AddField(
            model_name='settings',
            name='footer_logo',
            field=models.ImageField(blank=True, upload_to=frontend.models.upload_image_path, verbose_name='Footer Logo'),
        ),
        migrations.AddField(
            model_name='settings',
            name='header_logo',
            field=models.ImageField(blank=True, upload_to=frontend.models.upload_image_path, verbose_name='Header Logo'),
        ),
        migrations.AddField(
            model_name='settings',
            name='img_sec_four',
            field=models.ImageField(blank=True, upload_to=frontend.models.upload_image_path, verbose_name='IMG Section four'),
        ),
        migrations.AddField(
            model_name='settings',
            name='img_sec_one',
            field=models.ImageField(blank=True, upload_to=frontend.models.upload_image_path, verbose_name='IMG Section one'),
        ),
        migrations.AddField(
            model_name='settings',
            name='img_sec_three',
            field=models.ImageField(blank=True, upload_to=frontend.models.upload_image_path, verbose_name='IMG Section three'),
        ),
        migrations.AddField(
            model_name='settings',
            name='img_sec_two',
            field=models.ImageField(blank=True, upload_to=frontend.models.upload_image_path, verbose_name='IMG Section two'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='slider_video_url',
            field=models.URLField(blank=True, verbose_name='Slider Video URL'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
