# Generated by Django 4.1.5 on 2023-02-21 18:29

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subproduct",
            name="title_img",
            field=models.ImageField(
                blank=True, null=True, upload_to=products.models.upload_image_path
            ),
        ),
    ]
