# Generated by Django 4.1.5 on 2023-02-22 08:10

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_images_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproduct',
            name='header_bg_img',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_path),
        ),
    ]
