# Generated by Django 4.1.5 on 2023-02-22 08:16

from django.db import migrations, models

import products.models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_subproduct_header_bg_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainproduct",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="mainproduct",
            name="header_bg_img",
            field=models.ImageField(
                default="", upload_to=products.models.upload_image_path
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mainproduct",
            name="product_img",
            field=models.ImageField(upload_to=products.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name="subproduct",
            name="header_bg_img",
            field=models.ImageField(upload_to=products.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name="subproduct",
            name="header_img",
            field=models.ImageField(upload_to=products.models.upload_image_path),
        ),
        migrations.AlterField(
            model_name="subproduct",
            name="title_img",
            field=models.ImageField(upload_to=products.models.upload_image_path),
        ),
    ]
