# Generated by Django 4.1.5 on 2023-04-03 20:19

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_mainproduct2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='SubProductGallery',
        ),
        migrations.CreateModel(
            name='MainProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to=products.models.upload_image_path)),
                ('main_product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.mainproduct2')),
            ],
        ),
    ]
