# Generated by Django 4.1.5 on 2023-04-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_rename_images_subproductgallery_mainproductgallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainproduct2",
            name="short_description",
            field=models.TextField(default=""),
        ),
    ]
