# Generated by Django 4.1.5 on 2023-04-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_alter_mainproduct_create_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subproduct",
            name="short_description",
            field=models.TextField(default=""),
        ),
    ]
